# Generated by Django 3.1.4 on 2021-01-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotifications',
            fields=[
                ('templateId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('template', models.CharField(max_length=600)),
            ],
            options={
                'db_table': 'EmailNotifications',
            },
        ),
    ]
