# Generated by Django 3.1.4 on 2020-12-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('emailId', models.EmailField(max_length=100)),
                ('createdBy', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField()),
                ('isDeleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
