# Generated by Django 3.1.4 on 2020-12-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_user_refreshtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refreshToken',
            field=models.CharField(max_length=100),
        ),
    ]
