# Generated by Django 3.1.4 on 2020-12-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20201228_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refreshToken',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
