# Generated by Django 3.1.4 on 2020-12-21 19:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiSelectQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('difficultyLevel', models.IntegerField(default=0)),
                ('options', models.JSONField()),
                ('correctAns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('questionId', models.CharField(max_length=100)),
                ('subjectId', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'MultiSelectQA',
            },
        ),
        migrations.CreateModel(
            name='SingleSelectQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('difficultyLevel', models.IntegerField(default=0)),
                ('options', models.JSONField()),
                ('correctAns', models.CharField(max_length=50)),
                ('questionId', models.CharField(max_length=100)),
                ('subjectId', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'SingleSelectQA',
            },
        ),
        migrations.CreateModel(
            name='WaitageOfQuestions',
            fields=[
                ('subjectId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('totalNumberQuestions', models.IntegerField()),
                ('unknownNoQuestions', models.IntegerField(default=0)),
                ('easyNoQuestions', models.IntegerField(default=0)),
                ('mediumNoQuestions', models.IntegerField(default=0)),
                ('hardNoQuestions', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'WaitageOfQuestions',
            },
        ),
    ]
