# Generated by Django 3.1.4 on 2021-01-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fng_exam_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singleselectqa',
            old_name='options',
            new_name='optionA',
        ),
        migrations.AddField(
            model_name='multiselectqa',
            name='optionsA',
            field=models.JSONField(default='abcd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiselectqa',
            name='optionsB',
            field=models.JSONField(default='abcd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiselectqa',
            name='optionsC',
            field=models.JSONField(default='abcd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiselectqa',
            name='optionsD',
            field=models.JSONField(default='abcd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singleselectqa',
            name='optionB',
            field=models.JSONField(default='abcd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singleselectqa',
            name='optionC',
            field=models.JSONField(default='bced'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singleselectqa',
            name='optionD',
            field=models.JSONField(default='bcjhb'),
            preserve_default=False,
        ),
    ]
