# Generated by Django 3.1.4 on 2021-01-26 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fng_exam_app', '0003_auto_20210126_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiselectqa',
            name='options',
        ),
    ]
