# Generated by Django 3.1.4 on 2021-01-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fng_exam_app', '0004_remove_multiselectqa_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiselectqa',
            name='optionsA',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='multiselectqa',
            name='optionsB',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='multiselectqa',
            name='optionsC',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='multiselectqa',
            name='optionsD',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='singleselectqa',
            name='optionA',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='singleselectqa',
            name='optionB',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='singleselectqa',
            name='optionC',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='singleselectqa',
            name='optionD',
            field=models.CharField(max_length=200),
        ),
    ]
